require 'httparty'
require 'slugify'
require 'viddl-rb'

require_relative 'get_freaky/conference'
require_relative 'get_freaky/error_object'
require_relative 'get_freaky/event'
require_relative 'get_freaky/info'
require_relative 'get_freaky/null_conference'
require_relative 'get_freaky/null_event'
require_relative 'get_freaky/version'
require_relative 'get_freaky/video'
